version: "3"

services:
  redis:
    container_name: mwf_redis
    image: redis

  app:
    container_name: mwf_app

    build: ./source/app

    volumes:
      - ./source/app:/app
      - M:/mus/gp:/gp

    environment:
      PORT: 3000

    depends_on:
      - redis

    ports:
      - "3000:3000"

    hostname: app.docker

  python-app:
    container_name: mwf_python_app

    build: ./source/python-server

    ports:
      - "8000:8000"

    hostname: py.docker

  frontend:
    container_name: mwf_frontend

    build: ./source/frontend

    volumes:
      - ./source/frontend:/app

    environment:
      CHOKIDAR_USEPOLLING: "true"

    depends_on:
      - app

    ports:
      - "3001:3000"

    hostname: front.docker
