version: "3"

# Live Reloading: https://betterprogramming.pub/live-reloading-with-docker-compose-for-efficient-development-356d50e91e39
# Docker-compose: идеальное рабочее окружение https://habr.com/ru/post/346086/

services:
  redis:
    container_name: sandbox_redis
    image: redis

    hostname: redis.docker

  node-app:
    container_name: sandbox_node_app

    build: ./source/app

    volumes:
      - ./source/app:/app
      - M:/mus/gp:/gp

    environment:
      PORT: 80

    depends_on:
      - redis

    ports:
      - "3001:80"

    hostname: app.docker

  python-app:
    container_name: sandbox_python_app

    build: ./source/python-server

    volumes:
      - ./source/python-server:/app

    ports:
      - "8111:80"

    hostname: py.docker

  php-app:
    container_name: sandbox_php_app

    image: bitnami/php-fpm:latest

    volumes:
      - ./source/php:/app

    ports:
      - "9000:9000"

    hostname: php.docker

  frontend:
    container_name: sandbox_frontend

    build: ./source/frontend

    volumes:
      - ./source/frontend:/app

    environment:
      CHOKIDAR_USEPOLLING: "true"

    depends_on:
      - node-app
      - php-app
      - python-app

    ports:
      - "3000:80"

    hostname: front.docker
