version: "3"

services:
  redis:
    container_name: mwf_redis
    image: redis

    hostname: redis.docker

  node-app:
    container_name: mwf_node_app

    build: ./source/app

    volumes:
      - ./source/app:/app
      - M:/mus/gp:/gp

    environment:
      PORT: 80

    depends_on:
      - redis

    ports:
      - "3001:80"

    hostname: app.docker

  python-app:
    container_name: mwf_python_app

    build: ./source/python-server

    volumes:
      - ./source/python-server:/app

    ports:
      - "8111:80"

    hostname: py.docker

  php-app:
    container_name: mwf_php_app

    build: ./source/php

    volumes:
      - ./source/php:/app

    ports:
      - "8000:80"

    hostname: php.docker

  frontend:
    container_name: mwf_frontend

    build: ./source/frontend

    volumes:
      - ./source/frontend:/app

    environment:
      CHOKIDAR_USEPOLLING: "true"

    depends_on:
      - node-app
      - php-app
      - python-app

    ports:
      - "3000:80"

    hostname: front.docker
